export const metadata = {
    title: 'Academic Homepage',
    description: 'Generated by create next app',
    icons: {
        icon: '/assets/ph_icon.svg',
    },
};

import './global.css';
import React from 'react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}

